# Generated by Django 3.2.18 on 2023-03-02 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vtb_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vtb_name', models.CharField(default='Hiiro', max_length=114, verbose_name='名称')),
                ('vtb_price', models.FloatField(default=114514.1919, verbose_name='价格')),
                ('vtb_exp', models.IntegerField(default=233, verbose_name='次数')),
                ('vtb_reborn', models.BooleanField(default=False, verbose_name='转生')),
                ('vtb_age', models.DateField(auto_now_add=True, verbose_name='时间')),
            ],
            options={
                'verbose_name': 'Vtb名称',
                'verbose_name_plural': 'Vtb名称',
                'db_table': 'vtb_info',
            },
        ),
        migrations.CreateModel(
            name='Ski_info_A',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ski_name', models.CharField(default='王牛奶拳', max_length=114, verbose_name='Vtb名称')),
                ('ski_cost', models.FloatField(default=5.14, verbose_name='消耗')),
                ('ski_damage', models.FloatField(default=19.19, verbose_name='伤害')),
                ('ski_cold', models.IntegerField(default=2.4, verbose_name='冷却')),
                ('ski_last', models.IntegerField(default=0.02, verbose_name='持续')),
                ('Vtb_info', models.ForeignKey(db_column='Vtb_info', on_delete=django.db.models.deletion.CASCADE, to='App_07.vtb_info', verbose_name='Ski名称')),
            ],
            options={
                'verbose_name': 'Ski名称',
                'verbose_name_plural': 'Ski名称',
                'db_table': 'ski_info',
            },
        ),
    ]
