# Generated by Django 3.2.18 on 2023-03-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_07', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vtb_info',
            name='vtb_image',
            field=models.ImageField(null=True, upload_to='vtb_image', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='ski_info_a',
            name='ski_cold',
            field=models.FloatField(default=2.4, verbose_name='冷却'),
        ),
        migrations.AlterField(
            model_name='ski_info_a',
            name='ski_last',
            field=models.FloatField(default=0.02, verbose_name='持续'),
        ),
    ]
